name: CytrilDuel
version: '1.1.1'
main: com.cytril.duel.CytrilDuel
api-version: '1.21'
author: Cytril
softdepend: [PlaceholderAPI]

commands:
  duel:
    description: Sistem duel CytrilDuel
    usage: /duel [accept|deny|cancel|setarena|setlobby|setkit|spectatorradius|stats|top|reload|settings]
  party:
    description: Sistem party CytrilDuel
    usage: /party [invite|accept|deny|leave|list]

permissions:
  cytrilduel.admin:
    description: Akses admin CytrilDuel (setarena, setlobby, setkit, dll)
    default: op
  cytrilduel.use:
    description: Akses dasar duel & party
    default: true
